# Default template
template: "default"

# Databases
databases:
  - name: "test-db"
    url: "mysql://root:12345678@localhost:3306/test1"
  - name: "test-db2"
    url: "mysql://root:12345678@localhost:3306/test2"